[paras_optim_order, fval] = fmincon(@(paras_orders) ...
        cish_obj_fun_meta(paras_orders, vars_fit_name, vars_all, u0), ...
        paras_orders0, A, b, Aeq, beq, ...
        paras_orders_lb, paras_orders_ub, ...
        nonlcon, options);